# Generated by Django 4.2.5 on 2023-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_user_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
