# Generated by Django 4.2.5 on 2023-09-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_sentença_sentenca"),
    ]

    operations = [
        migrations.AddField(
            model_name="acordo",
            name="risco_provavel",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="acordo",
            name="valor_causa",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="acordo",
            name="valor_pedido",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="processo",
            name="acordos",
            field=models.ManyToManyField(related_name="processos", to="app.acordo"),
        ),
        migrations.AddField(
            model_name="processo",
            name="advogados",
            field=models.ManyToManyField(related_name="processos", to="app.advogado"),
        ),
        migrations.AddField(
            model_name="processo",
            name="reus",
            field=models.ManyToManyField(related_name="processos", to="app.reu"),
        ),
        migrations.AddField(
            model_name="processo",
            name="sentencas",
            field=models.ManyToManyField(related_name="processos", to="app.sentenca"),
        ),
        migrations.AlterField(
            model_name="acordo",
            name="valor_acordo",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
