# Generated by Django 4.2.4 on 2023-09-14 14:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_acordo_risco_provavel_acordo_valor_causa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reu',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='sentenca',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='acordos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='advogados',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='reus',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='sentencas',
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_numero_oab',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número da OAB deve estar no formato correto (XXXX/UF). Exemplo: 1234/AB.', regex='^\\d{4,6}/\\w+$')]),
        ),
        migrations.AddField(
            model_name='processo',
            name='autor_cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='autor_data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processo',
            name='autor_endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='autor_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_acordo',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 14, 44, 0, 615912, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_sentenca',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processo',
            name='descricao_acordo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='descricao_sentenca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='reu_cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='reu_data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='processo',
            name='reu_endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='reu_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_acordo',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_sentenca',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_causa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_risco_provavel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero_processo',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Acordo',
        ),
        migrations.DeleteModel(
            name='Advogado',
        ),
        migrations.DeleteModel(
            name='Reu',
        ),
        migrations.DeleteModel(
            name='Sentenca',
        ),
    ]
