# Generated by Django 4.2.4 on 2023-09-14 15:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_processo_data_abertura_processo_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='advogado_nome',
            new_name='advogado_adv_nome',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='advogado_numero_oab',
            new_name='advogado_adverso_numero_oab',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='advogado_cpf',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='advogado_data_nascimento',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='advogado_endereco',
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_agressor',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_colaborador_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='advogado_colaborador_numero_oab',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número da OAB deve estar no formato correto (XXXX/UF). Exemplo: 1234/AB.', regex='^\\d{4,6}/\\w+$')]),
        ),
        migrations.AddField(
            model_name='processo',
            name='coligacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='numero_dossie',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='obj_padrao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo_de_acao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_acordo',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 15, 29, 42, 561991, tzinfo=datetime.timezone.utc)),
        ),
    ]
