# Generated by Django 4.2.4 on 2023-09-14 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_advogado_nome_processo_advogado_adv_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_acordo',
            field=models.DateField(default=datetime.datetime(2023, 9, 14, 16, 47, 31, 688558, tzinfo=datetime.timezone.utc)),
        ),
    ]
