# Generated by Django 4.2.4 on 2023-09-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_processo_autor_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='advogado_adv_nome',
            new_name='advogado_adverso',
        ),
        migrations.RenameField(
            model_name='processo',
            old_name='advogado_colaborador_nome',
            new_name='advogado_colaborador',
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_acordo',
            field=models.DateField(default=datetime.datetime(2023, 9, 15, 15, 9, 42, 101758, tzinfo=datetime.timezone.utc)),
        ),
    ]
