# Generated by Django 4.2.5 on 2023-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_processo_advogado_centralizador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="valor_contingencia",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
