# Generated by Django 4.2.5 on 2023-09-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_processo_valor_contingencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="pasta_antiga",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
