# Generated by Django 4.2.5 on 2023-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_remove_processo_tribunal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="ult_desdobramento",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
