# Generated by Django 4.2.5 on 2023-09-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_processo_ult_desdobramento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processo",
            name="autor_contumaz",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="processo",
            name="terceiro_interessado",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="processo",
            name="terceiro_prestador",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
