from import_export import resources
from .models import Processo

class ProcessoResource(resources.ModelResource):
    class Meta:
        model = Processo
        fields = (
            'data_cadastro',
            'numero_dossie',
            'pasta_antiga',
            'natureza',
            'empresa_origem',
            'coligada',
            'agencia_departamento',
            'area',
            'tipo_de_acao',
            'objeto_padrao',
            'fase',
            'inserido_por',
            'alterado_por',
            'data_de_alt',
            'palavra_chave',
            'valor_estimado',
            'valor_contingencia',
            'valor_causa',
            'valor_pedido',
            'valor_risco_possivel',
            'valor_risco_provavel',
            'risco_provavel_s_atu',
            'valor_contingencia_civel',
            'data_estimada_prev',
            'data_estimada_pgto',
            'valor_risco',
            'risco',
            'total_pago',
            'inss_empresa',
            'honorarios',
            'custas_processuais',
            'situacao',
            'nome_desdobramento',
            'data_ajuizamento',
            'ult_desdobramento',
            'instancia',
            'rito',
            'juizo',
            'orgao',
            'comarca',
            'uf',
            'numero',
            'cliente',
            'cond_cliente',
            'parte_adversa',
            'cond_adversa',
            'cpf_cnpj_adversa',
            'autor_contumaz',
            'motivo_desligamento',
            'cargo',
            'terceiro_interessado',
            'terceiro',
            'terceiro_prestador',
            'cpf_cnpj_terceiro_prestador',
            'adv_cred',
            'adv_adverso',
            'adv_agressor',
            'handle_perito',
            'perito',
            'data_encerramento',
            'motivo_encerramento',
            'exito',
            'id_benner',
            'data_evento',
            'evento',
            'tarefas',
            'adv_centralizador',
            'v_risco_remoto',
            'observacao',
            'data_atualizada',
            'alterado_por_auditor',
            'data_alteracao_auditor',
            'danos',
            'assunto',
            'responsabilidade',
            'causas_especiais',
            'solic_enc_em',
            'pendencias',
            'inserido_por_evento',
            'perc_controlador',
            'perc_ex_controlador',
            'revisao',
            'solic_enc_por',
            'tipo_desligamento',
            'adv_colaborador',
            'equipe',
            'data_do_fato',
            'data_de_alteracao_da_fase',
            'subarea',
            'encerrado_em',
            'encerrado_por',
            'valor_acordo',
            'rede',
            'regional',
            'canal_de_contratacao',
            'valor_condenacao_atual',
            'valor_encerramento',
            'valor_contabil_geral',
            'diferenca_encerramento',
            'porcentagem_diferenca_enc',
            'indice_atualizacao',
        )

    skip_unchanged = True
    report_skipped = False
    import_id_fields = ['numero_processo']
